export interface DiagnosticQuestion {
  id: number;
  tier: 1 | 2 | 3;
  tierName: "Foundations (A2/B1)" | "Core B1" | "B1+/B2 Gateways";
  topic: string;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
}

export const DIAGNOSTIC_30_QUESTIONS: DiagnosticQuestion[] = [
  // ===================== TIER 1: Foundations (A2/B1 - Check for core decay) =====================
  {
    id: 1,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Present Perfect vs Past Simple",
    question: "I ______ in this apartment since 2022, and I really enjoy the neighborhood.",
    options: ["am living", "have lived", "lived", "was living"],
    correctAnswer: "have lived",
    explanation: "Use Present Perfect ('have lived') with 'since' for an action that started in the past and continues into the present.",
  },
  {
    id: 2,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Past Simple with Specific Time",
    question: "Last night at 8 PM, I ______ dinner with my family.",
    options: ["have had", "had", "was having", "have been having"],
    correctAnswer: "had",
    explanation: "Use Past Simple ('had') for a completed past action associated with a specific past time ('Last night').",
  },
  {
    id: 3,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "For vs Since",
    question: "She has been studying graphic design ______ three months.",
    options: ["since", "during", "for", "from"],
    correctAnswer: "for",
    explanation: "Use 'for' with a duration / period of time ('three months'), and 'since' with a specific starting point.",
  },
  {
    id: 4,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Relative Pronouns",
    question: "The woman ______ car was damaged in the storm called her insurance company.",
    options: ["who", "which", "whose", "that"],
    correctAnswer: "whose",
    explanation: "Use 'whose' to express possession ('whose car' = the woman's car).",
  },
  {
    id: 5,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "State vs Action Verbs",
    question: "Right now, I ______ this exercise is quite straightforward.",
    options: ["am believing", "believe", "believed", "have believed"],
    correctAnswer: "believe",
    explanation: "'Believe' is a stative verb expressing mental state, so it is rarely used in continuous (-ing) tenses.",
  },
  {
    id: 6,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Comparatives",
    question: "This laptop is ______ than my old desktop computer.",
    options: ["much more fast", "far faster", "more faster", "faster much"],
    correctAnswer: "far faster",
    explanation: "Short adjectives add '-er' ('faster'). Use 'far' or 'much' as modifiers to emphasize the degree ('far faster').",
  },
  {
    id: 7,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Much / Many / A Lot Of",
    question: "We didn't receive ______ feedback on our initial project proposal.",
    options: ["many", "much", "a few", "several"],
    correctAnswer: "much",
    explanation: "'Feedback' is an uncountable noun, so use 'much' in negative statements ('didn't receive much feedback').",
  },
  {
    id: 8,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Present Perfect with Just/Already/Yet",
    question: "Have you finished preparing the presentation ______?",
    options: ["already", "just", "yet", "still"],
    correctAnswer: "yet",
    explanation: "Use 'yet' at the end of questions and negative sentences in the Present Perfect.",
  },
  {
    id: 9,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Future Intentions: Going to vs Will",
    question: "Look at those dark, heavy clouds in the sky! It ______ rain.",
    options: ["will", "is going to", "rains", "is raining"],
    correctAnswer: "is going to",
    explanation: "Use 'going to' for predictions based on present sensory evidence (dark storm clouds).",
  },
  {
    id: 10,
    tier: 1,
    tierName: "Foundations (A2/B1)",
    topic: "Prepositions of Place & Time",
    question: "Our international conference takes place ______ July 15th.",
    options: ["in", "at", "on", "by"],
    correctAnswer: "on",
    explanation: "Use 'on' for specific calendar dates and days of the week ('on July 15th').",
  },

  // ===================== TIER 2: Core B1 Competencies =====================
  {
    id: 11,
    tier: 2,
    tierName: "Core B1",
    topic: "Past Continuous & Past Simple Narrative",
    question: "While I ______ down the street, my phone suddenly rang.",
    options: ["walked", "was walking", "have walked", "had walked"],
    correctAnswer: "was walking",
    explanation: "Past Continuous ('was walking') describes an ongoing background action interrupted by a shorter action ('rang').",
  },
  {
    id: 12,
    tier: 2,
    tierName: "Core B1",
    topic: "Past Perfect Sequencing",
    question: "By the time the train pulled into the station, the passengers ______ on the platform for 40 minutes.",
    options: ["waited", "were waiting", "had waited", "have waited"],
    correctAnswer: "had waited",
    explanation: "Past Perfect indicates an event or duration that occurred before another event in the past ('pulled into').",
  },
  {
    id: 13,
    tier: 2,
    tierName: "Core B1",
    topic: "Past Habits: Used to vs Would",
    question: "I ______ believe in ghosts when I was a young child, but I don't anymore.",
    options: ["would", "used to", "was used to", "use to"],
    correctAnswer: "used to",
    explanation: "For past states and stative verbs ('believe', 'know', 'live'), only 'used to' is possible; 'would' is only for repeated actions.",
  },
  {
    id: 14,
    tier: 2,
    tierName: "Core B1",
    topic: "First Conditional with Unless",
    question: "You will not make noticeable progress ______ you practice actively every week.",
    options: ["if", "unless", "provided", "in case"],
    correctAnswer: "unless",
    explanation: "'Unless' means 'if not' (You will not make progress if you do not practice).",
  },
  {
    id: 15,
    tier: 2,
    tierName: "Core B1",
    topic: "Second Conditional (Hypothetical Present)",
    question: "If I ______ more free time, I would take up a new language.",
    options: ["have", "had", "would have", "will have"],
    correctAnswer: "had",
    explanation: "Second Conditional structure: If + Past Simple ('had'), would + bare infinitive.",
  },
  {
    id: 16,
    tier: 2,
    tierName: "Core B1",
    topic: "Modals of Ability: Could vs Managed to",
    question: "Although the mountain trail was steep and dangerous, the hikers ______ reach safety before nightfall.",
    options: ["could", "managed to", "can", "might"],
    correctAnswer: "managed to",
    explanation: "To express ability on a specific past occasion requiring difficulty or struggle, use 'managed to' or 'was able to', not 'could'.",
  },
  {
    id: 17,
    tier: 2,
    tierName: "Core B1",
    topic: "Present Perfect Continuous (Duration)",
    question: "Her eyes are red because she ______ computer screens for hours.",
    options: ["looks at", "has been looking at", "had looked at", "is looking at"],
    correctAnswer: "has been looking at",
    explanation: "Present Perfect Continuous ('has been looking at') highlights continuous duration with visible present results.",
  },
  {
    id: 18,
    tier: 2,
    tierName: "Core B1",
    topic: "Phrasal Verbs in Context",
    question: "We had to ______ the meeting until next Tuesday because the director was sick.",
    options: ["call off", "put off", "look after", "turn down"],
    correctAnswer: "put off",
    explanation: "'Put off' means to postpone or delay to a later time.",
  },
  {
    id: 19,
    tier: 2,
    tierName: "Core B1",
    topic: "Defining vs Non-Defining Clauses",
    question: "My sister, ______ lives in Berlin, is visiting us next weekend.",
    options: ["that", "which", "who", "whom"],
    correctAnswer: "who",
    explanation: "In non-defining relative clauses (with commas), you cannot use 'that' for people — use 'who'.",
  },
  {
    id: 20,
    tier: 2,
    tierName: "Core B1",
    topic: "Modals of Obligation: Must vs Have to",
    question: "In the UK, drivers ______ drive on the left-hand side of the road by law.",
    options: ["must", "have to", "should", "ought to"],
    correctAnswer: "have to",
    explanation: "'Have to' is standard for external rules, laws, and official regulations.",
  },

  // ===================== TIER 3: B1+ / B2 Gateways (Transition to B2) =====================
  {
    id: 21,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Third Conditional (Past Regrets)",
    question: "If we ______ the train schedule earlier, we wouldn't have missed our departure.",
    options: ["checked", "had checked", "would check", "would have checked"],
    correctAnswer: "had checked",
    explanation: "Third Conditional 'if' clause requires Past Perfect ('had checked') for an unreal past condition.",
  },
  {
    id: 22,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Mixed Conditionals",
    question: "If I had moved to London last year, I ______ fluent in English right now.",
    options: ["would have been", "would be", "will be", "had been"],
    correctAnswer: "would be",
    explanation: "Mixed Conditional: Past condition ('had moved') with a present result ('would be right now').",
  },
  {
    id: 23,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Passive Voice in Complex Tenses",
    question: "The confidential report ______ by the auditor when the power went out.",
    options: ["was reviewing", "was being reviewed", "had reviewed", "has been reviewed"],
    correctAnswer: "was being reviewed",
    explanation: "Past Continuous Passive: was/were + being + past participle ('was being reviewed').",
  },
  {
    id: 24,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Causative Verbs (Have/Get Done)",
    question: "My smartphone screen cracked, so I ______ it repaired at the store yesterday.",
    options: ["made", "had", "did", "let"],
    correctAnswer: "had",
    explanation: "Causative structure: have/get + object + past participle ('had it repaired').",
  },
  {
    id: 25,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Past Modals of Deduction",
    question: "Sarah didn't answer any calls or emails all afternoon. She ______ asleep.",
    options: ["must be", "must have been", "can't be", "should have been"],
    correctAnswer: "must have been",
    explanation: "'Must have been' expresses strong logical certainty about a past event.",
  },
  {
    id: 26,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Gerund vs Infinitive Semantic Shifts",
    question: "On her long road trip, she stopped ______ gasoline and stretch her legs.",
    options: ["getting", "to get", "get", "for getting"],
    correctAnswer: "to get",
    explanation: "'Stop to do' means interrupt an activity in order to do something else. ('Stop doing' means quit doing it).",
  },
  {
    id: 27,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Wish / If Only for Past Regrets",
    question: "I really wish I ______ my phone charger before leaving on this trip.",
    options: ["packed", "had packed", "would pack", "pack"],
    correctAnswer: "had packed",
    explanation: "Wish about the past requires the Past Perfect: 'wish I had packed'.",
  },
  {
    id: 28,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Dependent Prepositions",
    question: "The project manager insisted ______ reviewing the code before release.",
    options: ["in", "on", "at", "about"],
    correctAnswer: "on",
    explanation: "The verb 'insist' always pairs with the preposition 'on' ('insist on doing something').",
  },
  {
    id: 29,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Contrast Linkers (Despite / Although)",
    question: "______ the severe snowstorm, the flight landed safely on time.",
    options: ["Although", "Despite", "Even though", "In spite"],
    correctAnswer: "Despite",
    explanation: "'Despite' is followed directly by a noun phrase ('the severe snowstorm'). 'Although' requires a full clause with a verb.",
  },
  {
    id: 30,
    tier: 3,
    tierName: "B1+/B2 Gateways",
    topic: "Indirect / Embedded Questions",
    question: "Could you please tell me what time ______?",
    options: ["does the supermarket close", "the supermarket closes", "closes the supermarket", "is the supermarket closing"],
    correctAnswer: "the supermarket closes",
    explanation: "Indirect questions use statement word order (Subject + Verb: 'the supermarket closes'), without auxiliary inversion.",
  },
];
