import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// The 60-Quest Roadmap curated from Cambridge English Profile & Murphy's English Grammar
export const ROADMAP_DATA = [
  // ===================== WORLD 1: Consolidation & Narrative Mastery (B1 → B1+) =====================
  {
    world: 1,
    orderIndex: 1,
    title: "Present Perfect vs Past Simple",
    description: "Connect past experience to present consequences vs fixed points in past time.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q1_1",
        type: "mcq",
        question: "I ______ in this city for three years now, and I still love it.",
        options: ["lived", "have lived", "was living", "am living"],
        correctAnswer: "have lived",
        explanation: "Use Present Perfect ('have lived') for an action that started in the past and continues into the present.",
      },
      {
        id: "q1_2",
        type: "fill_blank",
        question: "Yesterday at 5 PM, she ______ (finish) the quarterly report.",
        correctAnswer: "finished",
        explanation: "Past Simple is used with specific finished past time expressions ('Yesterday at 5 PM').",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 2,
    title: "Past Continuous & Past Perfect in Storytelling",
    description: "Master background actions vs completed prior actions to build engaging narratives.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q2_1",
        type: "mcq",
        question: "When I arrived at the cinema, the movie ______ already ______.",
        options: ["was / starting", "has / started", "had / started", "is / starting"],
        correctAnswer: "had / started",
        explanation: "Past Perfect ('had started') refers to an event that happened before another past event ('arrived').",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 3,
    title: "Habitual Past: Used to vs Would vs Be Used to",
    description: "Express past states, past habits, and familiarization with natural precision.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q3_1",
        type: "mcq",
        question: "I ______ live in London when I was a child. (State verb)",
        options: ["would", "used to", "was used to", "use to"],
        correctAnswer: "used to",
        explanation: "'Used to' works with states and habits. 'Would' can only be used for past actions, not state verbs like 'live' or 'know'.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 4,
    title: "Defining vs Non-Defining Relative Clauses",
    description: "Provide vital identification or extra supplementary details with correct comma usage.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q4_1",
        type: "mcq",
        question: "My brother, ______ lives in Toronto, is visiting next weekend.",
        options: ["that", "who", "which", "whom"],
        correctAnswer: "who",
        explanation: "In non-defining relative clauses (with commas), you cannot use 'that' for people — use 'who'.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 5,
    title: "Present Perfect Continuous: Duration vs Result",
    description: "Differentiate ongoing activities ('I have been reading') from finished results ('I have read').",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q5_1",
        type: "fill_blank",
        question: "Her eyes are tired because she has been ______ (read) all morning.",
        correctAnswer: "reading",
        explanation: "Present Perfect Continuous focuses on the continuous duration and physical side effects of an action.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 6,
    title: "Essential B1+ Phrasal Verbs in Context",
    description: "Master multi-word verbs: come across, look forward to, put off, bring up.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q6_1",
        type: "mcq",
        question: "We had to ______ the meeting until Friday due to unforeseen circumstances.",
        options: ["put off", "put out", "take over", "call off"],
        correctAnswer: "put off",
        explanation: "'Put off' means to postpone or reschedule to a later date.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 7,
    title: "Modals of Ability and Permission across Tenses",
    description: "Express ability and permission in the past and future: could vs was able to vs managed to.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q7_1",
        type: "mcq",
        question: "Despite the heavy blizzard, the climbers ______ reach the summit.",
        options: ["could", "were able to", "can", "might"],
        correctAnswer: "were able to",
        explanation: "For a specific past achievement requiring effort in a difficult situation, use 'was/were able to' or 'managed to', not 'could'.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 8,
    title: "Comparatives & Superlatives: Nuanced Modifiers",
    description: "Qualify comparisons with far, significantly, slightly, by far, nowhere near as.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q8_1",
        type: "mcq",
        question: "The second exam was ______ more difficult than the first one.",
        options: ["very", "significantly", "more", "too"],
        correctAnswer: "significantly",
        explanation: "Use adverbs of degree like 'significantly', 'considerably', or 'slightly' to modify comparatives.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 9,
    title: "Future Forms: Intentions, Predictions & Arrangements",
    description: "Select between Will, Going to, Present Continuous, and Present Simple for future reference.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q9_1",
        type: "mcq",
        question: "Look at those dark storm clouds! It ______ rain.",
        options: ["will", "is going to", "rains", "is raining"],
        correctAnswer: "is going to",
        explanation: "Use 'going to' when making a prediction based on present physical evidence.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 10,
    title: "Cohesion: Narrative Linking Words",
    description: "Connect complex story arcs with meanwhile, eventually, as soon as, prior to.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q10_1",
        type: "fill_blank",
        question: "He worked tirelessly for 10 months and ______ (eventual) launched his own company.",
        correctAnswer: "eventually",
        explanation: "'Eventually' indicates an outcome that occurred after a long struggle or delay.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 11,
    title: "B1+ Collocations for Daily Life & Work",
    description: "Form natural combinations: make an effort, take advantage of, pay attention to.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q11_1",
        type: "mcq",
        question: "You should really ______ advantage of this internship opportunity.",
        options: ["make", "take", "do", "get"],
        correctAnswer: "take",
        explanation: "The standard collocation is 'take advantage of'.",
      },
    ]),
  },
  {
    world: 1,
    orderIndex: 12,
    title: "🏆 Boss Challenge 1: The Narrative Arc Exam",
    description: "Comprehensive checkpoint on all narrative tenses, habit structures, and B1+ cohesion.",
    skill: "writing",
    isBoss: true,
    quizData: JSON.stringify([
      {
        id: "boss1_1",
        type: "mcq",
        question: "By the time the police arrived, the suspect ______.",
        options: ["escaped", "had escaped", "was escaping", "has escaped"],
        correctAnswer: "had escaped",
        explanation: "Past Perfect is required for the earlier past event.",
      },
      {
        id: "boss1_2",
        type: "fill_blank",
        question: "Rewrite using 'used to': I lived in Madrid when I was young. -> I ______ (live) in Madrid.",
        correctAnswer: "used to live",
        explanation: "'used to live' accurately expresses the past state.",
      },
    ]),
  },

  // ===================== WORLD 2: Hypotheticals & Speculation (B1+ → B2 Entry) =====================
  {
    world: 2,
    orderIndex: 13,
    title: "Zero & First Conditionals + Advanced Linkers",
    description: "Go beyond 'if': master unless, provided that, as long as, on condition that.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q13_1",
        type: "mcq",
        question: "You won't pass the exam ______ you review your vocabulary daily.",
        options: ["if", "provided that", "unless", "as long as"],
        correctAnswer: "unless",
        explanation: "'Unless' means 'if not' (If you don't review your vocabulary).",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 14,
    title: "Second Conditional: Unreal Present & Future",
    description: "Formulate hypothetical ideas, advice ('If I were you'), and improbable scenarios.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q14_1",
        type: "mcq",
        question: "If I ______ more time, I would take up painting.",
        options: ["have", "had", "would have", "will have"],
        correctAnswer: "had",
        explanation: "Second conditional clause requires Past Simple (If + past simple, would + infinitive).",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 15,
    title: "Third Conditional: Past Counterfactuals & Regrets",
    description: "Reflect on unchangeable past outcomes with If + past perfect, would have + past participle.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q15_1",
        type: "fill_blank",
        question: "If she had left earlier, she ______ (not miss) the flight.",
        correctAnswer: "would not have missed",
        explanation: "Third conditional main clause requires 'would have + past participle'.",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 16,
    title: "Mixed Conditionals: The Classic B2 Leap",
    description: "Combine past actions with present consequences (Past cause -> Present result).",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q16_1",
        type: "mcq",
        question: "If I had taken that job in Tokyo last year, I ______ in Japan right now.",
        options: ["would have lived", "would be living", "will live", "had lived"],
        correctAnswer: "would be living",
        explanation: "Mixed conditional: Past condition ('had taken') with a present result ('would be living right now').",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 17,
    title: "Wishes & Regrets: Wish / If Only",
    description: "Differentiate present wishes ('wish I had') from past regrets ('wish I had known').",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q17_1",
        type: "mcq",
        question: "I really wish I ______ to my teacher's advice yesterday.",
        options: ["listened", "had listened", "would listen", "listen"],
        correctAnswer: "had listened",
        explanation: "Regret about a past event requires 'wish + Past Perfect'.",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 18,
    title: "Modals of Deduction: Present Speculation",
    description: "Express degrees of certainty: Must be, Can't be, Might / Could / May be.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q18_1",
        type: "mcq",
        question: "The lights are completely off and nobody answers the door. They ______ at home.",
        options: ["must be", "can't be", "should be", "could be"],
        correctAnswer: "can't be",
        explanation: "'Can't be' expresses logical impossibility in the present.",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 19,
    title: "Past Modals of Deduction & Criticism",
    description: "Analyze past events: Must have been, Can't have been, Should have done.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q19_1",
        type: "mcq",
        question: "Alex didn't answer my calls all evening. He ______ asleep.",
        options: ["must have been", "should be", "can't have been", "was being"],
        correctAnswer: "must have been",
        explanation: "'Must have been' expresses strong logical certainty about a past event.",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 20,
    title: "Speculative Vocabulary & Hedging",
    description: "Express nuance using presumably, undoubtedly, in all likelihood, tentatively.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q20_1",
        type: "mcq",
        question: "In all ______, the flight will be delayed due to technical maintenance.",
        options: ["likelihood", "possibility", "chance", "probability"],
        correctAnswer: "likelihood",
        explanation: "The idiomatic phrase is 'in all likelihood' (meaning almost certainly).",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 21,
    title: "Hypothetical Inversions: Had I known, Were I...",
    description: "Elevate formal register with conditional inversion without 'if'.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q21_1",
        type: "fill_blank",
        question: "Rewrite without 'if': If you should need any assistance, contact me. -> ______ you need any assistance, contact me.",
        correctAnswer: "Should",
        explanation: "Inverted 1st conditional: 'Should you need...'",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 22,
    title: "Expressing Preferences: Would rather vs Prefer",
    description: "Select structures: prefer doing to doing vs would rather do than do.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q22_1",
        type: "mcq",
        question: "I would rather ______ dinner at home tonight than go out.",
        options: ["to have", "have", "having", "had"],
        correctAnswer: "have",
        explanation: "'Would rather' is followed by a bare infinitive ('have').",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 23,
    title: "Idioms & Expressions for Risk and Uncertainty",
    description: "Incorporate B2 idiomatic language: on thin ice, in the balance, play it safe.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q23_1",
        type: "mcq",
        question: "With three minutes remaining, the outcome of the match hung ______.",
        options: ["in the air", "in the balance", "on the line", "at stake"],
        correctAnswer: "in the balance",
        explanation: "'Hang in the balance' means uncertain or undecided.",
      },
    ]),
  },
  {
    world: 2,
    orderIndex: 24,
    title: "🏆 Boss Challenge 2: The Speculative Case Study",
    description: "Demonstrate mixed conditionals, past deduction, and speculative vocabulary under test conditions.",
    skill: "writing",
    isBoss: true,
    quizData: JSON.stringify([
      {
        id: "boss2_1",
        type: "mcq",
        question: "If we ______ the contract last month, we wouldn't be in financial trouble today.",
        options: ["signed", "had signed", "would sign", "were signing"],
        correctAnswer: "had signed",
        explanation: "Mixed conditional requires past perfect 'had signed' for the past cause.",
      },
    ]),
  },

  // ===================== WORLD 3: Objectivity & Academic Impersonality (B2 Core) =====================
  {
    world: 3,
    orderIndex: 25,
    title: "Passive Voice in All Verb Forms & Modals",
    description: "Shift focus from agent to action across present perfect, continuous, and modal passives.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q25_1",
        type: "mcq",
        question: "The documents ______ by the legal team right now.",
        options: ["are reviewed", "are being reviewed", "have reviewed", "were reviewed"],
        correctAnswer: "are being reviewed",
        explanation: "Present Continuous Passive: 'are being reviewed'.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 26,
    title: "Causative Verbs: Have/Get Something Done",
    description: "Express actions arranged through third parties vs doing them yourself.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q26_1",
        type: "fill_blank",
        question: "My laptop was broken, so I had it ______ (repair) yesterday.",
        correctAnswer: "repaired",
        explanation: "Causative structure: have + object + past participle ('had it repaired').",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 27,
    title: "Impersonal Reporting Passives",
    description: "Sound objective: It is widely believed that... / The CEO is reported to have resigned.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q27_1",
        type: "mcq",
        question: "The ancient artifact is believed ______ over 3,000 years old.",
        options: ["that it is", "to be", "being", "having been"],
        correctAnswer: "to be",
        explanation: "Personal passive structure: Subject + passive verb + to-infinitive ('is believed to be').",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 28,
    title: "Gerund vs Infinitive: Crucial Semantic Shifts",
    description: "Control meaning differences with remember, stop, forget, regret, try.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q28_1",
        type: "mcq",
        question: "On the way to work, he stopped ______ a cup of coffee.",
        options: ["buying", "to buy", "buy", "for buying"],
        correctAnswer: "to buy",
        explanation: "'Stop to do something' means pause an action in order to do something else.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 29,
    title: "Participle Clauses (-ing and -ed reductions)",
    description: "Condense subordinate clauses: 'Having finished the report, she left the office.'",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q29_1",
        type: "mcq",
        question: "______ in 1920, the historic bridge is undergoing preservation.",
        options: ["Constructed", "Constructing", "Having constructed", "To construct"],
        correctAnswer: "Constructed",
        explanation: "Past participle clause replaces a passive relative clause ('Which was constructed in 1920').",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 30,
    title: "Advanced Concession & Contrast Linkers",
    description: "Balance arguments: In spite of / Despite + noun, Whereas, Nevertheless, Nonetheless.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q30_1",
        type: "mcq",
        question: "______ the torrential rain, the marathon proceeded as scheduled.",
        options: ["Although", "Despite", "Even though", "In spite"],
        correctAnswer: "Despite",
        explanation: "'Despite' is followed directly by a noun phrase, unlike 'Although' which needs a clause.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 31,
    title: "Academic Register & Nominalization",
    description: "Transform informal verbs into formal noun phrases (decide -> make a decision).",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q31_1",
        type: "fill_blank",
        question: "The company reacted quickly. -> The company's quick ______ (react) prevented a crisis.",
        correctAnswer: "reaction",
        explanation: "Nominalization turns verbs into nouns to create formal, concise prose.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 32,
    title: "Dependent Prepositions: B2 Word Combinations",
    description: "Master target prepositions: capable OF, insist ON, prone TO, compensate FOR.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q32_1",
        type: "mcq",
        question: "The director insisted ______ inspecting the facilities personally.",
        options: ["in", "on", "at", "for"],
        correctAnswer: "on",
        explanation: "The verb 'insist' takes the preposition 'on' ('insist on doing').",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 33,
    title: "Verbs of Perception with Bare Infinitive vs Gerund",
    description: "Differentiate completed actions ('saw him cross') from ongoing ones ('saw him crossing').",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q33_1",
        type: "mcq",
        question: "I heard someone ______ quietly outside my door.",
        options: ["to whisper", "whispering", "whispered", "whispers"],
        correctAnswer: "whispering",
        explanation: "Verbs of perception take a participle (-ing) to describe an action in progress.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 34,
    title: "Impersonal Structures with Dummy 'It'",
    description: "Master stylistic structures: It occurs to me that..., It turns out that...",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q34_1",
        type: "fill_blank",
        question: "It never occurred ______ me that she might decline the offer.",
        correctAnswer: "to",
        explanation: "The phrase is 'It occurs to someone that...'",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 35,
    title: "Prefixes & Suffixes for Word Formation",
    description: "Solve Cambridge FCE Reading Part 3 word formation puzzles systematically.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q35_1",
        type: "fill_blank",
        question: "The sudden ______ (appear) of the witness shocked the jury.",
        correctAnswer: "appearance",
        explanation: "Suffix '-ance' forms a noun from the verb 'appear'.",
      },
    ]),
  },
  {
    world: 3,
    orderIndex: 36,
    title: "🏆 Boss Challenge 3: The Formal Report",
    description: "Write and evaluate an objective, impersonal report using passive voice and discourse connectors.",
    skill: "writing",
    isBoss: true,
    quizData: JSON.stringify([
      {
        id: "boss3_1",
        type: "mcq",
        question: "The project is expected ______ completed ahead of schedule.",
        options: ["being", "to be", "having been", "that it is"],
        correctAnswer: "to be",
        explanation: "'Is expected to be completed' is the standard passive reporting structure.",
      },
    ]),
  },

  // ===================== WORLD 4: Nuance, Register & Emphasis (B2 Solidification) =====================
  {
    world: 4,
    orderIndex: 37,
    title: "Advanced Reporting Verbs & Structures",
    description: "Move past 'said': master urge, deny + ing, blame someone for, apologize for.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q37_1",
        type: "mcq",
        question: "He strongly denied ______ the confidential files.",
        options: ["to leak", "having leaked", "leak", "leaked"],
        correctAnswer: "having leaked",
        explanation: "'Deny' is followed by a gerund or perfect gerund ('having leaked').",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 38,
    title: "Indirect & Embedded Questions for Politeness",
    description: "Sound diplomatic: 'Could you tell me what time the flight departs?' (No inversion).",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q38_1",
        type: "mcq",
        question: "Do you happen to know where ______?",
        options: ["does the manager work", "the manager works", "works the manager", "is working the manager"],
        correctAnswer: "the manager works",
        explanation: "Indirect questions use statement word order (Subject + Verb), never question inversion.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 39,
    title: "Negative Inversions for Dramatic Emphasis",
    description: "Master literary fronting: Never have I..., Seldom do we..., Not only... but also.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q39_1",
        type: "fill_blank",
        question: "Never in my life ______ (I / see) such a breathtaking sunrise.",
        correctAnswer: "have I seen",
        explanation: "Negative fronting triggers auxiliary-subject inversion: 'have I seen'.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 40,
    title: "Cleft Sentences: Highlighting Information",
    description: "Focus attention: 'What shocked me was...' / 'It was his determination that succeeded.'",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q40_1",
        type: "mcq",
        question: "______ impressed the interview panel was her analytical problem-solving.",
        options: ["That", "What", "Which", "It"],
        correctAnswer: "What",
        explanation: "Wh-cleft sentence: 'What impressed the panel was...'",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 41,
    title: "Future Continuous vs Future Perfect",
    description: "Map actions in progress in the future ('will be working') vs completed milestones ('will have finished').",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q41_1",
        type: "fill_blank",
        question: "By next December, she ______ (graduate) from university.",
        correctAnswer: "will have graduated",
        explanation: "Use Future Perfect ('will have graduated') with 'By + future time'.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 42,
    title: "The Subjunctive in Formal English",
    description: "Use base forms in recommendations: 'The doctor advised that he rest for 3 days.'",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q42_1",
        type: "mcq",
        question: "It is essential that every candidate ______ on time.",
        options: ["arrives", "arrive", "will arrive", "arrived"],
        correctAnswer: "arrive",
        explanation: "The formal present subjunctive uses the base infinitive form ('arrive').",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 43,
    title: "Phrasal Verbs with Multiple Meanings & Particles",
    description: "Navigate 3-part phrasal verbs: look down on, cut down on, run out of, get away with.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q43_1",
        type: "mcq",
        question: "The criminal managed to get away ______ his fraudulent transactions.",
        options: ["from", "with", "for", "by"],
        correctAnswer: "with",
        explanation: "'Get away with' means escape punishment for an wrongdoing.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 44,
    title: "Question Tags for Nuanced Intonation",
    description: "Differentiate real checks (rising tone) from seeking agreement (falling tone).",
    skill: "speaking",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q44_1",
        type: "fill_blank",
        question: "You haven't told anyone about this surprise, ______ you?",
        correctAnswer: "have",
        explanation: "Negative statement takes an affirmative tag: 'haven't -> have you?'.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 45,
    title: "Register Shifting: Informal to Formal Translation",
    description: "Replace conversational filler with elevated academic phrasing.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q45_1",
        type: "mcq",
        question: "Replace 'deal with': The committee needs to ______ this issue immediately.",
        options: ["handle", "address", "touch", "take care"],
        correctAnswer: "address",
        explanation: "'Address an issue' is the professional B2 academic standard.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 46,
    title: "Collocations: Abstract Adjective + Noun Combinations",
    description: "Acquire high-scoring chunks: profound impact, pressing issue, fierce debate.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q46_1",
        type: "mcq",
        question: "Artificial intelligence has had a ______ impact on modern workflow.",
        options: ["heavy", "profound", "sharp", "thick"],
        correctAnswer: "profound",
        explanation: "'Profound impact' is an established B2/C1 collocation.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 47,
    title: "Hedging & Diplomatic Disagreement in Speaking",
    description: "Politely challenge opinions: 'I see your point, however...', 'Up to a point, but...'",
    skill: "speaking",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q47_1",
        type: "mcq",
        question: "I agree with you up to a ______, but we must consider the budget constraints.",
        options: ["limit", "point", "level", "degree"],
        correctAnswer: "point",
        explanation: "'Up to a point' is used to show partial agreement.",
      },
    ]),
  },
  {
    world: 4,
    orderIndex: 48,
    title: "🏆 Boss Challenge 4: The Debate & Rhetoric Trial",
    description: "Defend arguments using cleft sentences, inversions, and advanced reporting verbs.",
    skill: "speaking",
    isBoss: true,
    quizData: JSON.stringify([
      {
        id: "boss4_1",
        type: "fill_blank",
        question: "Seldom ______ (we / encounter) such remarkable artistic talent.",
        correctAnswer: "have we encountered",
        explanation: "Negative inversion requires auxiliary verb before subject.",
      },
    ]),
  },

  // ===================== WORLD 5: Exam Readiness & Transformation (B2+ Final Target) =====================
  {
    world: 5,
    orderIndex: 49,
    title: "Key Word Transformation: Passive & Causative Tricks",
    description: "Crack Cambridge FCE Part 4: Rephrase sentences with 2-5 words including the key word.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q49_1",
        type: "fill_blank",
        question: "They are painting our house. [HAVING] -> We ______ our house painted.",
        correctAnswer: "are having",
        explanation: "Key Word Transformation: 'are having our house painted'.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 50,
    title: "Key Word Transformation: Conditionals & Wishes",
    description: "Master FCE transformations: 'had it not been for', 'provided that', 'wish I had'.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q50_1",
        type: "fill_blank",
        question: "Without your advice, I would have failed. [FOR] -> Had it ______ your advice, I would have failed.",
        correctAnswer: "not been for",
        explanation: "'Had it not been for' is the gold-standard FCE conditional transformation.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 51,
    title: "Key Word Transformation: Comparisons & Inversions",
    description: "Transform: 'nowhere near as', 'such a... that', 'no sooner had... than'.",
    skill: "grammar",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q51_1",
        type: "fill_blank",
        question: "The second task was much harder than the first. [NEARLY] -> The first task was ______ as the second.",
        correctAnswer: "not nearly as hard",
        explanation: "'not nearly as hard as' conveys the comparative difference.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 52,
    title: "Essay Architecture: Hook, Arguments & Counter-Arguments",
    description: "Structure a 190-word B2 essay with introduction, 2 balanced points, counterpoint, and synthesis.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q52_1",
        type: "mcq",
        question: "Where should the thesis statement ideally be positioned in an academic essay?",
        options: ["First sentence of introduction", "At the end of introduction", "In body paragraph 1", "Only in the conclusion"],
        correctAnswer: "At the end of introduction",
        explanation: "The thesis statement belongs at the end of the introductory paragraph.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 53,
    title: "Reading: Gapped Text Strategy (FCE Part 6)",
    description: "Identify cohesive links, pronoun references, and rhetorical sequence between paragraphs.",
    skill: "reading",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q53_1",
        type: "mcq",
        question: "When selecting a sentence to fill a gap in a text, what is the most reliable clue?",
        options: ["Matching vocabulary length", "Pronouns referencing the previous sentence", "Random guessing", "Ignoring surrounding sentences"],
        correctAnswer: "Pronouns referencing the previous sentence",
        explanation: "Reference pronouns ('this', 'they', 'such measures') establish logical cohesion across gaps.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 54,
    title: "Listening: Distractors & Paraphrase Traps",
    description: "Overcome listening traps: when speakers change their mind or use partial negation.",
    skill: "listening",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q54_1",
        type: "mcq",
        question: "A speaker says: 'I was tempted by the Italian course, but the schedule clashed, so I went for German.' Which language did they take?",
        options: ["Italian", "German", "Both", "Neither"],
        correctAnswer: "German",
        explanation: "Notice the pivot word 'but' which rejects the initial tempting option (Italian).",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 55,
    title: "Speaking: Collaborative Task & Negotiation",
    description: "Lead conversational turns in B2 pair speaking: 'Shall we move on to...', 'What do you reckon?'",
    skill: "speaking",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q55_1",
        type: "mcq",
        question: "Which phrase best initiates a smooth transition to the next topic in a pair discussion?",
        options: ["Stop talking now.", "Shall we move on to the next point?", "My turn to talk.", "I don't care about this."],
        correctAnswer: "Shall we move on to the next point?",
        explanation: "A collaborative transition invites your partner while advancing the agenda.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 56,
    title: "High-Tier B2 Phrasal Verbs & Idiomatic Expressions",
    description: "Integrate native-like expressions: bite the bullet, hit the nail on the head, read between the lines.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q56_1",
        type: "mcq",
        question: "Her explanation was accurate and directly addressed the core issue. She ______.",
        options: ["bit the bullet", "hit the nail on the head", "spilled the beans", "missed the boat"],
        correctAnswer: "hit the nail on the head",
        explanation: "'Hit the nail on the head' means to describe or identify a problem with exact accuracy.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 57,
    title: "Writing: The Formal Article vs The Informal Review",
    description: "Master register adaptability across reviews, articles, reports, and emails.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q57_1",
        type: "mcq",
        question: "Which closing is appropriate for a formal job application letter where you know the recipient's name (Mr. Henderson)?",
        options: ["Yours faithfully,", "Yours sincerely,", "Best wishes,", "Cheers,"],
        correctAnswer: "Yours sincerely,",
        explanation: "When the name is known, use 'Yours sincerely,'. When unknown ('Dear Sir/Madam'), use 'Yours faithfully,'.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 58,
    title: "Advanced Punctuation & Discourse Markers",
    description: "Utilize semicolons, em-dashes, and colons to organize complex compound-complex syntax.",
    skill: "writing",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q58_1",
        type: "mcq",
        question: "Which punctuation mark correctly connects two closely related independent clauses without a conjunction?",
        options: ["Comma", "Semicolon", "Hyphen", "Slash"],
        correctAnswer: "Semicolon",
        explanation: "A semicolon connects two independent clauses of equal grammatical weight.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 59,
    title: "Rapid Active Recall: B2 Lexical Speed Run",
    description: "60-second rapid-fire test across all 5 worlds of vocabulary, prepositions, and linkers.",
    skill: "vocabulary",
    isBoss: false,
    quizData: JSON.stringify([
      {
        id: "q59_1",
        type: "mcq",
        question: "She apologized sincerely ______ her unpunctual arrival.",
        options: ["about", "for", "to", "at"],
        correctAnswer: "for",
        explanation: "The collocation is 'apologize for doing something'.",
      },
    ]),
  },
  {
    world: 5,
    orderIndex: 60,
    title: "🏁 FINAL BOSS: Full B2+ CEFR Graduation Exam",
    description: "The ultimate 4-skill milestone assessment verifying solid B2/B2+ readiness for official examination.",
    skill: "grammar",
    isBoss: true,
    quizData: JSON.stringify([
      {
        id: "final_1",
        type: "mcq",
        question: "Had she known about the storm warnings, she ______ the ferry.",
        options: ["wouldn't take", "wouldn't have taken", "hadn't taken", "didn't take"],
        correctAnswer: "wouldn't have taken",
        explanation: "Inverted 3rd conditional: 'Had she known..., she wouldn't have taken'.",
      },
      {
        id: "final_2",
        type: "fill_blank",
        question: "Not only ______ (she / win) the regional prize, but she also set a tournament record.",
        correctAnswer: "did she win",
        explanation: "Negative fronting inversion in past simple: 'did she win'.",
      },
    ]),
  },
];

export async function seedRoadmapTopics() {
  console.log("🗺️ Seeding 60 Roadmap Quests across 5 Worlds...");

  for (const topic of ROADMAP_DATA) {
    await prisma.roadmapTopic.upsert({
      where: { id: topic.orderIndex },
      update: {
        world: topic.world,
        orderIndex: topic.orderIndex,
        title: topic.title,
        description: topic.description,
        skill: topic.skill,
        isBoss: topic.isBoss,
        quizData: topic.quizData,
      },
      create: {
        id: topic.orderIndex,
        world: topic.world,
        orderIndex: topic.orderIndex,
        title: topic.title,
        description: topic.description,
        skill: topic.skill,
        isBoss: topic.isBoss,
        quizData: topic.quizData,
      },
    });
  }

  // Ensure the student has the first topic unlocked by default
  const student = await prisma.user.findFirst({ where: { role: "student" } });
  if (student) {
    await prisma.userTopicProgress.upsert({
      where: { userId_topicId: { userId: student.id, topicId: 1 } },
      update: {},
      create: {
        userId: student.id,
        topicId: 1,
        status: "unlocked",
      },
    });
  }

  console.log("✅ 60 Roadmap Quests successfully seeded!");
}
